import { Box, Button, styled } from '@mui/material';
import { intelayerColors, intelayerFonts } from './theme';

export const TradingViewComponent = styled(Box)(() => ({
  display: 'flex',
  width: '100%',
  height: '100%',
  borderRadius: '12px',
  overflow: 'hidden',
  backgroundColor: intelayerColors.surface,
  border: `1px solid ${intelayerColors.panelBorder}`,
  '> div': {
    width: '100%',
    height: '100%',
    iframe: {
      border: 'none',
      width: '100%',
      height: '100%',
      backgroundColor: intelayerColors.surface,
    },
  },
  '@media (max-width: 1023px)': {
    position: 'relative',
    height: 'auto',
    paddingTop: '60%',
    '> div': {
      position: 'absolute',
      inset: 0,
      height: '100%',
    },
  },
}));

export const ChatBox = styled(Box)(() => ({
  display: 'flex',
  flexDirection: 'column',
  gap: '12px',
  width: '100%',
  minHeight: '280px',
  height: '100%',
  '.header_nav': {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '8px',
  },
  header: {
    fontFamily: intelayerFonts.heading,
    fontSize: '15px',
    fontWeight: 500,
    color: intelayerColors.ink,
  },
  '.chat_room': {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    flex: 1,
    minHeight: 0,
  },
  '.chat_messages': {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    overflowY: 'auto',
    flex: 1,
    padding: '4px 2px 4px 0',
  },
  '.chat_input': {
    display: 'flex',
    borderRadius: '10px',
    alignItems: 'center',
    border: `1px solid ${intelayerColors.panelBorder}`,
    padding: '0 12px',
    height: '40px',
    backgroundColor: intelayerColors.surface,
    input: {
      flex: 1,
      border: 'none',
      outline: 'none',
      background: 'transparent',
      color: intelayerColors.ink,
      fontFamily: intelayerFonts.body,
      fontSize: '14px',
    },
  },
  '.send_bubble': {
    alignSelf: 'flex-end',
    background: 'linear-gradient(135deg, #0EF09D33, #0EF09D0d)',
    border: `1px solid ${intelayerColors.green[500]}`,
    color: intelayerColors.ink,
    padding: '10px 12px',
    borderRadius: '14px',
    fontFamily: intelayerFonts.body,
    fontSize: '13px',
    maxWidth: '90%',
  },
  '.received_bubble': {
    alignSelf: 'flex-start',
    backgroundColor: intelayerColors.gray[700],
    color: intelayerColors.ink,
    padding: '10px 12px',
    borderRadius: '14px',
    fontFamily: intelayerFonts.body,
    fontSize: '13px',
    maxWidth: '90%',
  },
  '.image_bubble': {
    width: '100%',
    borderRadius: '12px',
    border: `1px solid ${intelayerColors.panelBorder}`,
  },
  '.image_status': {
    position: 'absolute',
    bottom: '8px',
    right: '8px',
    background: 'rgba(0, 0, 0, 0.7)',
    color: '#fff',
    borderRadius: '12px',
    padding: '4px 10px',
    fontSize: '12px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    boxShadow: `0 4px 12px ${intelayerColors.backdrop}`,
  },
  '.image_status-error': {
    background: 'rgba(214, 65, 65, 0.85)',
    color: '#fff',
  },
  '.extracted_card': {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    backgroundColor: intelayerColors.gray[700],
    border: `1px solid ${intelayerColors.panelBorder}`,
    borderRadius: '12px',
    padding: '10px 12px',
  },
  '.extracted_row': {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '13px',
    color: intelayerColors.ink,
    alignItems: 'center',
    gap: '12px',
    '.pill': {
      padding: '4px 8px',
      borderRadius: '10px',
      fontSize: '11px',
      textTransform: 'uppercase',
      letterSpacing: '0.4px',
    },
    '.pill-long': { backgroundColor: '#0ef09d1f', color: '#0EF09D' },
    '.pill-short': { backgroundColor: '#d24b4b1f', color: '#FF6961' },
  },
  '.warning_bubble': {
    padding: '10px 12px',
    borderRadius: '12px',
    border: `1px solid ${intelayerColors.panelBorder}`,
    backgroundColor: '#3b2b2b',
    color: '#FFB4A2',
  },
  '.typing': {
    color: intelayerColors.muted,
    fontSize: '12px',
    padding: '6px 10px',
  },
  '&.drag-active': {
    border: `1px dashed ${intelayerColors.green[500]}`,
  },
}));

export const BtnWithIcon = styled(Button)(() => ({
  padding: 0,
  minWidth: '36px',
  height: '36px',
  borderRadius: '8px',
  backgroundColor: intelayerColors.green[600],
  '&:hover': {
    backgroundColor: intelayerColors.green[500],
  },
}));
